### ISSUE TITLE
cpu_tsdf cannot compile with pcl 1.8.1

### ISSUE THREAD

**Issue by ZhipengRobot** [sdmiller/cpu_tsdf#33]
Hi

In the beginning, I  compiled cpu_tsdf with pcl 1.8.1. Then I ran the demo application "integrate", and I got a segmentation fault. Then I recompiled cpu_tsdf with pcl 1.7.2, everything is fine. I do not know how to change the code to make it compatible with pcl 1.8.1. Could you help me?

Thank you very much!

**Comment by sdmiller** [comment]
Hi Zhipeng,

Hmmm, I'm afraid I'm not sure offhand. If it's a segmentation fault, I imagine this has less to do with PCL compatibility (that would be a compiler error) and more some symbol clash with a library we both share. Maybe the boost version we're depending on is different?

**Comment by ipa-jcl-dc** [comment]
Hi 

I also had the same problem with you. It only works for 1.7.2

**Comment by sdmiller** [comment]
Very interesting. It seems either something I'm using is broken in pcl 1.8.1 (Marching Cubes is really the only thing I can think of that was actually using any PCL code, beyond containers), or there's a clash due to some duplicate symbol.

I wish I were still on a linux box to help debug this -- maybe I can get on one at some point. Otherwise I'd be grateful for anyone who can catch this in gdb to help narrow down the issue.

**Comment by sdmiller** [comment]
Interesting, I just ran it against 1.8.1 on OSX and didn't get a crash. Digging in...

**Comment by dbadrian** [comment]
For me compiling against PCL 1.7.2 instead of the latest fixed a segfault when running this line
```c++
    cpu_tsdf::TSDFVolumeOctree::Ptr tsdf (new cpu_tsdf::TSDFVolumeOctree);
```

**Comment by sdmiller** [comment]
Aha interesting! I still haven't been able to reproduce this, but you've given me a clue.

If it's in the constructor, that suggests to me some unaligned memory. I know Eigen has some memory alignment issues when a class has a fixed size member: https://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html

I see TSDFVolumeOctree has an Eigen::Affine3d member with no such guard. It could be random that 1.8.1 provokes this (i.e. just something to do with how memory happens to be positioned.)

Could someone experiencing this crash on 1.8.1 please try https://github.com/sdmiller/cpu_tsdf/pull/39 and let me know if it still exists?

**Comment by sdmiller** [comment]
(tagging @dbadrian @ipa-jcl-dc and @ZhipengRobot :) )

**Comment by dbadrian** [comment]
Good catch, seems to have been the problem.
